services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_teste
    ports:
      - "8009:80"  # Altere a porta externa para 8080
    volumes:
      - .:/var/www/html
      - ./apache-config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - teste_network
    depends_on:
      - postgres

  # Serviço PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres_teste
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - teste_network

networks:
  teste_network:

volumes:
  pgdata: